config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :posts do
    member do
      put "like",to: "post#like"
      put "unlike",to: "post#unlike"
    end
    resources :comments
   end
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :users
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :likes
  has_many :comments
  has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/public/missing.png"
    validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_many :posts
  has_many :comments
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

         has_attached_file :image, styles: { thumb: "80x80>",mini: "25x25>" }, default_url: "/images/:style/missing.png"
         validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
end

app/controllers/application_controller.rb
require "application_responder"

class ApplicationController < ActionController::Base
  self.responder = ApplicationResponder
  respond_to :html

  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if:  :devise_controller?

protected
def configure_permitted_parameters
  devise_parameter_sanitizer.permit(:sign_up, keys: [:name,:image])
end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]
  before_action :set_post

  # GET /comments
  # GET /comments.json
  def index
    @comments = @post.comments.all
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    @comment = @post.comments.new
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments
  # POST /comments.json
  def create
    @comment = @post.comments.build(comment_params)
    @comment.user= current_user

    respond_to do |format|
      if @comment.save
        format.js
        format.html { redirect_to @post, notice: 'Comment was successfully created.' }
        format.json { render :show, status: :created, location: @comment }
      else
        format.html { render :new }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @comment, notice: 'Comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to comments_url, notice: 'Comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post=Post.find(params[:post_id])
      #@comment = @post.comments.find(params[:id])
    end

    def set_comment
      @comment = @post.comments.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:bdy)
    end
end

app/controllers/helpers/application_helper.rb
module ApplicationHelper
end

app/controllers/helpers/posts_helper.rb
module PostsHelper
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy,:kontrol,:like,:unlike]
  before_action :authenticate_user!
  before_action :kontrol, only: [:edit,:destroy]
  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

 def kontrol
      redirect_to root_path, notice:"Yetki" unless current_user.yetki==false
 end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @likeds=Like.where(post: @post).all
    @comments=@post.comments.all
  end

  def like
    @l=Like.new
    @l.post=@post
    @l.user=current_user
    @l.save
    respond_to do |format|
      format.js {render layout: false}
      format.json
    end
  end

  def unlike
    @l=Like.where(post:@post,user:current_user).first
    @l.destroy
    respond_to do |format|
      format.js {render layout: false}
      format.json
    end
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)
    @post.tarih=DateTime.now
@post.user=current_user
    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    @post.tarih=DateTime.now
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :makale, :tarih , :image)
    end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_form.html.erb
<div class="row">
<div class="col-md-6">
<%= form_for([@post, Comment.new], :remote=>'true', :controller => 'comments', :action => 'create') do |f| %>
<div class="row">
 <div class="col-md-9">
  <div class="form-group">
    <%= f.text_field :bdy, id: :comment_bdy, class:"form-control" %>
  </div>
  </div>
  <div class="col-md-3">
  <div class="actions">
    <%= f.submit "Yorum At", class:"form-action btn btn-info"  %>
  </div>
</div>
</div>
<% end %>
</div>
</div>

app/views/comments/create.js.erb
$('#comments').append('<%=image_tag @comment.user.image.url(:mini) if @comment.user.image? %> <em><%=@comment.user.name%> </em> <b> <%=@comment.bdy%> </b><br/>');

app/views/comments/edit.html.erb
<h1>Editing Comment</h1>

<%= render 'form', comment: @comment %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Comments</h1>

<table>
  <thead>
    <tr>
      <th>Bdy</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.bdy %></td>
        <td><%= link_to 'Show', comment %></td>
        <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comment', new_comment_path %>

app/views/comments/new.html.erb
<h1>New Comment</h1>

<%= render 'form', comment: @comment %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Bdy:</strong>
  <%= @comment.bdy %>
</p>

<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Web</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav>
      <p class="pid">PROFİLE</p>|
      <%=render 'devise/shared/navbar'%>
      <br>
      <br>
    </nav>
      <br>
    <%= yield %>
    <footer>
    <center>  <h1>Rails Ortam Değişkenleri</h1></center>
    <center>
      <%request.env.each do|key,value|%>
      <strong><%=key%></strong>=><%=value%> <br/>
      <%end%>
    </center>
    </footer>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_with(model: post, local: true) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, id: :post_title %>
  </div>

  <div class="field">
    <%= form.label :makale %>
    <%= form.text_area :makale, id: :post_makale %>
  </div>
  <div class="field">
      <%= form.label :image %><br>
      <%= form.file_field :image%>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<div class="container">
        <div class="row">
          <% @posts.each do |post| %>
            <div class="panel panel-default widget">

                <div class="panel-body">
                    <ul class="list-group">
                        <li class="list-group-item">
                            <div class="row">
                                <div class="col-xs-10 col-md-11">
                                  <div class="comment-text">
                                      <p id="notice"><%= notice %></p>
                                      <h1>Posts</h1>
                                          <% @posts.each do |post| %>
                                              <h1><%= post.title %> </br></h1>
                                              <h3> <%= post.makale %></br></h3>
                                              <h5><%= post.tarih %></br></h5>
                                              <%= image_tag post.image.url(:thumb)%>
                                          <% end %>
                                      <br>
                                    </div>
                                    <div class="action">
                                      <%if current_user.yetki?%>
                                      <%= link_to '', post, :method => :delete, data: {confirm: 'Eminmisin?',commit: 'Evet'},class:"glyphicon glyphicon-trash" %>
                                      <%= link_to '', edit_post_path(post),class:"glyphicon glyphicon-pencil" %>

                                      <%end%>
                                      <%= link_to '', post_path(post),class:"glyphicon glyphicon-hand-right" %>
                                        <hr width="100%" color="#990033" size="4">
                                    </div>
                                </div>
                            </div>
                            <%if current_user.yetki?%>
                            <%= link_to 'New Post', new_post_path %>
                            <%end%>
                        </li>
                    </ul>
                </div>
            </div>
            <%end%>
        </div>
    </div>

app/views/posts/like.js.erb
$('#<%=@post.id%>').html('<%= link_to "", unlike_post_path(@post), class:"glyphicon glyphicon-heart",remote: :true, method: :put %>')

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<div class="panel panel-default widget">

    <div class="panel-body">
        <ul class="list-group">
            <li class="list-group-item">
                <div class="row">

                    <div class="col-xs-10 col-md-11">
                        <div class="comment-text">

                          <p id="notice"><%= notice %></p>

                          <p>
                            <strong>Title:</strong>
                            <%= @post.title %>
                          </p>

                          <p>
                            <strong>Makale:</strong>
                            <%= @post.makale %>
                          </p>

                          <p>
                            <strong>Tarih:</strong>
                            <%= @post.tarih%>
                          </p>
                          <p>
                            <strong>Image:</strong>
                            <%= image_tag @post.image.url(:thumb)%>
                          </p>

                        </div>
                        <hr>
                        <div class="action">
                            <%if current_user.yetki?%>
                          <%= link_to '', @post, :method => :delete, data: {confirm: 'Eminmisin?',commit: 'Evet'},class:"glyphicon glyphicon-trash" %>
                          <%= link_to '', edit_post_path(@post),class:"glyphicon glyphicon-pencil" %>
                          <%end%>

                        </div>
                        <hr>
                        <%=render 'comments/form'%>

                        <hr>
                        <div id="comments">
                        <%@comments.each do |c|%>
                         <%=image_tag c.user.image.url(:mini) if c.user.image?%> <em> <%=c.user.name%> </em> <b><%=c.bdy%> </b>    <br/>
                        <%end%>
                      </div>

                    </div>
            </li>
        </ul>
    </div>
</div>

app/views/posts/unlike.js.erb
$('#<%=@post.id%>').html('<%= link_to "", like_post_path(@post), class:"glyphicon glyphicon-heart-empty",remote: :true, method: :put %>')